### ISSUE TITLE
Model preparation

### ISSUE THREAD

**Issue by midofalasol** [TexasInstruments/edgeai-modeloptimization#1]
Hello!

Thank you for your outstanding work! But I have a question.

Do I need to rewrite the model forward function with torch.fx into a fully static control flow before using the pruning tool?

**Comment by mathmanu** [comment]
torch.fx.symbolic_trace is used to construct a graph inside - so your model needs to works with symbolic_trace.

CC: @parakh08

**Comment by mayberpf** [comment]
@mathmanu Thank you for your reply! I observed that torch.fx converted tensor to a proxy class when creating a PrunerModule. Some dynamic judgments that rely on the original tensor are not supported, which makes it difficult for the forward function.

**Comment by parakh08** [comment]
This is only required when you are attempting the channel pruning. It is based on symbolic tracing and thus dynamic layers would be creating issues. The input dependent variables usually cause the issue of being converted to proxy class.
Maybe you can try using the surgery tool to change the particular layer efficiently or change the forward function such that it becomes traceable.

**Comment by midofalasol** [comment]
@parakh08  Thank you very much for your response. I found out that `fx.symbolic_trace` will be called when `PruneModule` encapsulates the model. Does this mean that all pruning modes need to support symbol trace, not just channel pruning?

May I ask if there will be any sample of model optimization tools similar to [edgeai_mmdetection3d](https://github.com/TexasInstruments/edgeai-mmdetection3d) project in the future, such as pruning of pointpillar or centerpoint?

**Comment by parakh08** [comment]
@midofalasol Yeah, it was an error from my side, the model needs to be FX traceable in order to use Pruning. 
Currently, we have tested the pruning toolkit on few models using [edgeai-torchvision](edgeai-torchvision). We will be expanding on object detection algorithms and keep adding support for them in this toolkit itself.

**Comment by midofalasol** [comment]
OK, I get it, thanks.
I will close this issue. Looking forward to your future work.
